module.exports = {
    SUCCESSFULLY_COMPLETED: 0,
    INVALID_TOKEN: 20,
    NO_TOKEN_PROVIDED: 25,
    NO_VALUE_FOUND: 30,
    EMPTY_FIELDS: 35,
    SUCCESSFULLY_AUTHENTIFIED: 40,
    USER_NOT_FOUND: 45,
    INCORRECT_PASSWORD: 50,
    EMAIL_ALREADY_EXISTS: 55,
    DATA_DUPLICATE: 60,

    //HTTP VERBS
    HTTP_OK: 200,
    HTTP_CREATED: 201,
    HTTP_NO_CONTENT: 204,
    HTTP_BAD_REQUEST: 400,
    HTTP_UNAUTHORIZED: 401,
    HTTP_ACCESS_DENIED: 403,
    HTTP_NOT_FOUND: 404,

    //URL
    API_VERSION: "/api/v1"
};